services:
  - type: web
    name: mmc-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mmc-postgres
          property: connectionString

  - type: pserv
    name: mmc-postgres
    env: postgres
    plan: free
    ipAllowList: []
